install.packages("devtools", repos='http://cran.us.r-project.org')
install.packages("roxygen2", repos='http://cran.us.r-project.org')
library(devtools)
library(roxygen2)
setwd("HOD")
document()
setwd("..")
install("HOD")
